### ISSUE TITLE
Fail to start

### ISSUE THREAD

**Issue by elioth010** [mthizo247/spring-cloud-netflix-zuul-websocket#1]
`***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method stompClient in com.github.mthizo247.cloud.netflix.zuul.web.socket.ZuulWebSocketConfiguration required a single bean, but 2 were found:
	- brokerMessageConverter: defined by method 'brokerMessageConverter' in org.springframework.web.socket.config.annotation.DelegatingWebSocketMessageBrokerConfiguration
	- datatypeChannelMessageConverter: defined in null

Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
`

Fail to start by dependency injection 
the pom is 

`<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-websocket</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.github.mthizo247</groupId>
			<artifactId>spring-cloud-netflix-zuul-websocket</artifactId>
			<version>1.0.0-RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-zuul</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-oauth2</artifactId>
		</dependency>
	</dependencies>`

my Application.java is 

`@EnableAutoConfiguration
@EnableDiscoveryClient
//@EnableZuulProxy
@EnableZuulWebSocket
@EnableWebSocketMessageBroker
@ComponentScan
public class Application {

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}
	
	@Bean
    public PreFilter preFilter() {
        return new PreFilter();
    }

}`

**Comment by mthizo247** [comment]
@elioth010 are you explicitly defining your own brokerMessageConverter? Could you somehow share the relevant code so I can take a look further. Thanks

**Comment by elioth010** [comment]
@mthizo247 sorry i use kafka and use a message broker, setting Qualifier to the bean i fix the issue, but a have a Question:  How do you integrate this to ribbon?

**Comment by mthizo247** [comment]
I have not yet tried integrating the library with ribbon, would be a great use case to try that out though...

**Comment by pal632022** [comment]
I am getting the same error as above. Can you please share the solution.
